# Lab 0: Làm quen với NumPy, Pandas và Matplotlib

Trước khi bước vào Deep Learning, ta cần ba người bạn không thể thiếu:

- **NumPy** — thư viện tính toán số học, chủ yếu là các phép trên mảng nhiều chiều. Mọi thứ trong PyTorch đều bắt nguồn từ ý tưởng của NumPy.
- **Pandas** — thao tác dữ liệu dạng bảng (DataFrame). Đọc CSV, lọc, gộp nhóm, biến đổi cột — tất cả là việc của Pandas.
- **Matplotlib** — vẽ đồ thị. Train một model mà không vẽ loss curve thì không khác gì lái xe nhắm mắt.

Bài này không có lý thuyết Deep Learning — nó là phần "khởi động cơ bắp". Cuối bài có một số bài tập để các em luyện tay. Đảm bảo làm xong và hiểu *trước khi* sang Lab 1.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)   # cố định seed để ai cũng ra cùng kết quả

## 1. NumPy

### 1.1. Tạo mảng và thuộc tính cơ bản

In [ ]:
a = np.array([1, 2, 3, 4])              # từ list
b = np.zeros((3, 4))                    # ma trận 3×4 toàn 0
c = np.ones(5)                          # vector 5 phần tử toàn 1
d = np.arange(0, 10, 2)                 # 0, 2, 4, 6, 8
e = np.linspace(0, 1, 5)                # 5 số đều từ 0 đến 1
f = np.random.rand(3, 3)                # ma trận 3×3 phân phối đều
g = np.random.randn(2, 3)               # ma trận 2×3 phân phối chuẩn

print('a shape:', a.shape, ' dtype:', a.dtype)
print('b =\n', b)
print('e =', e)
print('f =\n', f)
print('g =\n', g)

### 1.2. Reshape, indexing, slicing

In [32]:
x = np.arange(12)            # 0, 1, ..., 11
X = x.reshape(3, 4)
print('X =\n', X)

# Lấy phần tử (giống Python)
print('X[0, 0] =', X[0, 0])      # góc trên trái
print('X[1, 2] =', X[1, 2])      # hàng 1, cột 2

# Slicing: hàng 1, tất cả cột
print('X[1, :] =', X[1, :])

# Cột cuối cùng
print('X[:, -1] =', X[:, -1])

# Boolean indexing — cực kỳ hữu ích
mask = X > 5
print('mask =\n', mask)
print('X[X > 5] =', X[X > 5])

X =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
X[0, 0] = 0
X[1, 2] = 6
X[1, :] = [4 5 6 7]
X[:, -1] = [ 3  7 11]
mask =
 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
X[X > 5] = [ 6  7  8  9 10 11]


### 1.3. Broadcasting — phép màu của NumPy

Khi cộng hai mảng *khác shape*, NumPy tự động "kéo" mảng nhỏ ra cho khớp với mảng lớn (chừng nào shape phù hợp). Đây là tính năng giúp code rất ngắn gọn.

In [ ]:
M = np.arange(12).reshape(3, 4)        # (3, 4)
v = np.array([10, 20, 30, 40])         # (4,)

# v được broadcast lên thành (3, 4) rồi mới cộng.
print('M + v =\n', M + v)

# Trừ trung bình theo cột (zero-center) — kỹ thuật rất hay dùng trước khi train.
M_centered = M - M.mean(axis=0)
print('M_centered =\n', M_centered)
print('Mean theo cột:', M_centered.mean(axis=0))   # gần 0

### 1.4. Phép nhân ma trận và dot product

Phân biệt rõ:
- `*` là nhân từng phần tử (element-wise / Hadamard).
- `@` hoặc `np.dot` là nhân ma trận theo nghĩa tuyến tính.

Trong Deep Learning, các phép tính trong neural network đều là phép nhân ma trận — phải nhớ rõ chỗ này.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('A * B (element-wise) =\n', A * B)
print('A @ B (matrix mul)    =\n', A @ B)

# Dot product cho vector
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print('u . v =', u @ v)        # 4 + 10 + 18 = 32

### 1.5. Axis — chỗ hay nhầm nhất

Khi gọi `mean`, `sum`, `argmax`... với `axis=0` hay `axis=1`, mới học hay nhầm. Quy tắc đơn giản: **`axis=0` là gộp theo trục 0 → kết quả mất chiều 0**.

Với ma trận 2D: `axis=0` gộp các *hàng* lại (kết quả là 1 hàng); `axis=1` gộp các *cột* lại (kết quả là 1 cột).

In [ ]:
X = np.arange(12).reshape(3, 4)
print('X =\n', X)
print('Tổng tất cả        :', X.sum())
print('Tổng theo axis=0 (gộp hàng → 1 hàng):', X.sum(axis=0))   # shape (4,)
print('Tổng theo axis=1 (gộp cột → 1 cột):', X.sum(axis=1))    # shape (3,)
print('Argmax theo axis=1 :', X.argmax(axis=1))                 # vị trí max ở mỗi hàng

## 2. Pandas

### 2.1. Tạo DataFrame và xem nhanh

In [ ]:
df = pd.DataFrame({
    'name': ['An', 'Binh', 'Cuong', 'Dung', 'Em'],
    'age':  [20, 22, 21, np.nan, 23],
    'score': [8.5, 7.0, 9.0, 6.5, 8.0],
    'major': ['CNTT', 'CNTT', 'AI', 'AI', 'CNTT'],
})
df

In [ ]:
print(df.shape)            # (số hàng, số cột)
print(df.columns.tolist())
print(df.dtypes)
print()
df.describe()              # tóm tắt thống kê các cột số

### 2.2. `iloc` vs `loc` — phân biệt

- **`iloc`** dùng *vị trí số* (integer location), giống như indexing list/array Python.
- **`loc`** dùng *nhãn* (label).

Đây là chỗ nhiều người mới hay bị rối.

In [ ]:
print('df.iloc[0]      ← hàng có vị trí 0')
print(df.iloc[0])
print()
print('df.iloc[0:2]    ← 2 hàng đầu (KHÔNG bao gồm hàng 2)')
print(df.iloc[0:2])
print()
print('df.loc[0:2]     ← hàng có nhãn từ 0 đến 2 (BAO GỒM hàng 2)')
print(df.loc[0:2])
print()
print('df.loc[df["age"] > 21]  ← lọc theo điều kiện')
print(df.loc[df['age'] > 21])

### 2.3. Xử lý giá trị NaN

Dữ liệu thực tế hiếm khi sạch. NaN (Not a Number) là giá trị thiếu. Pandas có nhiều cách xử lý:

In [ ]:
print('Số NaN trong mỗi cột:')
print(df.isna().sum())
print()
print('Bỏ hàng có NaN:')
print(df.dropna())
print()
print('Điền NaN bằng giá trị trung bình của cột:')
print(df.fillna({'age': df['age'].mean()}))

### 2.4. GroupBy — gộp nhóm và tính thống kê

Một trong những tính năng mạnh nhất của Pandas. Cú pháp giống SQL `GROUP BY ... AGGREGATE`.

In [ ]:
# Trung bình điểm theo ngành
print(df.groupby('major')['score'].mean())
print()

# Nhiều phép gộp một lúc
print(df.groupby('major').agg(
    so_sinh_vien=('name', 'count'),
    diem_tb=('score', 'mean'),
    diem_max=('score', 'max'),
))

### 2.5. Đọc CSV — ví dụ với Iris

Cell này cần file `Iris.csv` (đã có sẵn trong thư mục `1. PyTorch/`).

In [ ]:
import os
iris_path = '1. PyTorch/Iris.csv'   # đường dẫn tương đối
if os.path.exists(iris_path):
    iris = pd.read_csv(iris_path)
    print(iris.head())
    print()
    print('Số mẫu mỗi loài:')
    print(iris['variety'].value_counts())
else:
    print(f'Không tìm thấy {iris_path} — bỏ qua phần này.')

## 3. Matplotlib

### 3.1. Đồ thị đường cơ bản

In [ ]:
x = np.linspace(0, 2 * np.pi, 200)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.figure(figsize=(8, 4))
plt.plot(x, y_sin, label='sin(x)', color='blue')
plt.plot(x, y_cos, label='cos(x)', color='red', linestyle='--')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Hàm sin và cos')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

### 3.2. Subplot — nhiều đồ thị trong một hình

Trong Deep Learning, ta hay phải vẽ "loss + accuracy" cạnh nhau để theo dõi training. Đó là lúc subplot lên ngôi.

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4))

axes[0].plot(x, np.sin(x))
axes[0].set_title('sin(x)')
axes[0].grid(alpha=0.3)

axes[1].plot(x, np.exp(-x/2) * np.sin(x))
axes[1].set_title('Sóng tắt dần exp(-x/2)·sin(x)')
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

### 3.3. Scatter và histogram

In [ ]:
# Scatter với màu phân lớp
X1 = np.random.randn(100, 2) + np.array([2, 2])
X2 = np.random.randn(100, 2) + np.array([-2, -2])

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].scatter(X1[:, 0], X1[:, 1], color='blue', label='Lớp A', alpha=0.6)
axes[0].scatter(X2[:, 0], X2[:, 1], color='red',  label='Lớp B', alpha=0.6)
axes[0].legend(); axes[0].set_title('Hai cụm điểm'); axes[0].grid(alpha=0.3)

# Histogram
axes[1].hist(np.random.randn(1000), bins=30, color='green', alpha=0.7)
axes[1].set_title('Phân phối chuẩn N(0, 1) — 1000 mẫu')
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

### 3.4. Lưu hình ra file

Khi viết báo cáo, em sẽ cần xuất hình ra file PNG hoặc PDF. Dùng `savefig()` *trước* `plt.show()`:

In [ ]:
plt.figure(figsize=(6, 4))
plt.plot(x, np.sin(x))
plt.title('Đồ thị mẫu')
# plt.savefig('my_plot.png', dpi=150, bbox_inches='tight')   # bỏ comment để lưu
plt.show()

# BÀI TẬP

Mỗi bài có hint, không có lời giải.

## Bài 1: NumPy cơ bản
1. Tạo mảng `a = np.arange(20)`. Lấy ra các phần tử ở vị trí chẵn (0, 2, 4...).
2. Tạo ma trận 5×5 toàn số 0, sau đó đặt 1 trên đường chéo chính (gợi ý: `np.eye` hoặc gán bằng `M[range(5), range(5)] = 1`).
3. Cho `M = np.random.randn(4, 5)`. Tính tổng theo từng hàng, theo từng cột. Kiểm tra shape kết quả có đúng `(4,)` và `(5,)` không.

## Bài 2: Broadcasting và normalize
Cho `X = np.random.randn(100, 4)` (100 mẫu, 4 đặc trưng). Hãy chuẩn hoá z-score *theo cột*: với mỗi cột, trừ trung bình rồi chia độ lệch chuẩn.
- Gợi ý: `X.mean(axis=0)` shape `(4,)`, dùng broadcasting để trừ đi.
- Sau khi chuẩn hoá, `X_normalized.mean(axis=0)` phải gần 0, `X_normalized.std(axis=0)` phải gần 1.

## Bài 3: Pandas — phân tích Iris
Đọc file `Iris.csv` (trong thư mục `1. PyTorch/`). Trả lời:
1. Có bao nhiêu dòng, bao nhiêu cột?
2. Trung bình `sepal.length` theo từng loài (variety) là bao nhiêu? (gợi ý: `groupby`)
3. Loài nào có `petal.width` lớn nhất?
4. Vẽ scatter plot 2D (`sepal.length` vs `petal.length`), tô màu theo loài.

## Bài 4: Matplotlib — vẽ learning curve giả
Sinh dữ liệu giả lập:
```python
epochs = np.arange(1, 51)
train_loss = 1.0 * np.exp(-epochs/10) + np.random.randn(50) * 0.02
test_loss  = 1.0 * np.exp(-epochs/12) + np.random.randn(50) * 0.03 + 0.05
```
Vẽ subplot 1×2:
- Trái: train_loss và test_loss qua epoch.
- Phải: histogram của các giá trị train_loss.

Có legend, label trục, title rõ ràng, grid mờ.

## Bài 5: Tổng hợp
Sinh 1000 điểm 2D từ 3 cụm Gaussian:
- Cụm A: tâm (0, 0), 300 điểm.
- Cụm B: tâm (4, 0), 300 điểm.
- Cụm C: tâm (2, 4), 400 điểm.

Mọi cụm có `std = 0.7`. Đặt vào DataFrame có cột `x, y, cluster`. Sau đó:
1. Vẽ scatter tô màu theo cụm.
2. Tính trung bình $(x, y)$ của mỗi cụm bằng `groupby` — kết quả có khớp với tâm gốc không?
3. Đếm số điểm trong mỗi cụm (kiểm tra 300/300/400).

## Bài 1: NumPy cơ bản

### 1. Tạo mảng `a = np.arange(20)`. Lấy ra các phần tử ở vị trí chẵn (0, 2, 4...).


In [4]:
import numpy as np
index_even = True
a = np.arange(20)
for i in a:
  if index_even:
    print(a[i])
  index_even = not index_even

0
2
4
6
8
10
12
14
16
18


### 2. Tạo ma trận 5×5 toàn số 0, sau đó đặt 1 trên đường chéo chính (gợi ý: `np.eye` hoặc gán bằng `M[range(5), range(5)] = 1`).

In [31]:
a = np.zeros((5,5))
i = 0
b, c= [a.copy() for _ in range(2)]
print('b.base:', b.base)
print('c.base:', c.base)


# Method 1.
while (i<5):
  b[i][i] = 1
  i+=1
print('Method 1:')
print(b, end='\n\n\n')


# Method 2.
c[range(5), range(5)] = 1
print('Method 2:')
print(c, end='\n\n\n')

# Method 3.
d = np.eye(5,5)
print('Method 3:')
print(d)

b.base: None
c.base: None
Method 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Method 2:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Method 3:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3. Cho `M = np.random.randn(4, 5)`. Tính tổng theo từng hàng, theo từng cột. Kiểm tra shape kết quả có đúng `(4,)` và `(5,)` không.


In [39]:
M = np.random.randn(4, 5)
print('M =', M, end='\n\n\n')
row_sums = M.sum(axis=1)
col_sums = M.sum(axis=0)
print('row_sums =', row_sums)
print('col_sums =', col_sums)
print('row_sums shape:', row_sums.shape)
print('col_sums shape:', col_sums.shape)

M = [[ 1.36839154  0.49646013  0.58814397 -1.73978001 -1.76032214]
 [-2.0497313   1.00739975 -0.50951919 -2.13485154  0.65161938]
 [ 2.55133768  1.13388106  1.48839448  0.16986955  1.23007986]
 [-0.70243437  0.05649237  0.75658003 -0.09644144  1.48643361]]


row_sums = [-1.0471065  -3.0350829   6.57356264  1.5006302 ]
col_sums = [ 1.16756356  2.69423331  2.32359929 -3.80120343  1.60781072]
row_sums shape: (4,)
col_sums shape: (5,)


## Bài 2: Broadcasting và normalize
Cho `X = np.random.randn(100, 4)` (100 mẫu, 4 đặc trưng). Hãy chuẩn hoá z-score *theo cột*: với mỗi cột, trừ trung bình rồi chia độ lệch chuẩn.
- Gợi ý: `X.mean(axis=0)` shape `(4,)`, dùng broadcasting để trừ đi.
- Sau khi chuẩn hoá, `X_normalized.mean(axis=0)` phải gần 0, `X_normalized.std(axis=0)` phải gần 1.


In [75]:
X = np.random.randn(100, 4)
col_means = X.mean(axis=0)

col_stds = np.array([])
X_normalized = np.array([])

for i in range(X.shape[1]):
  y,z = 0,0
  for j in range(X.shape[0]):
    x = X[j][i] - col_means[i]
    y+= pow(x,2)
  z = pow(y/(j+1),1/2)
  col_stds = np.append(col_stds, z)

del x,y,z
for i in range(X.shape[0]):
  for j in range(X.shape[1]):
    x = (X[i][j] - col_means[j])/col_stds[j]
    X_normalized = np.append(X_normalized, x)

X_normalized = X_normalized.reshape(X.shape[0],X.shape[1])

x = X_normalized.mean(axis=0)
y = X_normalized.std(axis=0)
print('X_normalized.mean(axis=0): ', x)
print('X_normalized.std(axis=0): ', y)


X_normalized.mean(axis=0):  [ 3.99680289e-17 -2.22044605e-17 -4.55191440e-17  2.99760217e-17]
X_normalized.std(axis=0):  [1. 1. 1. 1.]


In [76]:
import numpy as np

# Tạo lại ma trận ngẫu nhiên
X = np.random.randn(100, 4)

# Tính toán chuẩn bằng NumPy theo cột (axis=0)
col_means = X.mean(axis=0)
col_stds = X.std(axis=0)

# Ép công thức Z-score tự động cho toàn bộ ma trận
X_normalized = (X - col_means) / col_stds

# Kiểm tra lại kết quả
print('X_normalized.mean(axis=0): ', X_normalized.mean(axis=0))
print('X_normalized.std(axis=0):  ', X_normalized.std(axis=0))

X_normalized.mean(axis=0):  [-7.10542736e-17  2.32106001e-17 -5.55111512e-18  1.79370407e-17]
X_normalized.std(axis=0):   [1. 1. 1. 1.]
